### ISSUE TITLE
Not compatible anymore with Flow 2.3.8 and 3.0.2 security fix

### ISSUE THREAD

**Issue by coders-market** [mittwald/flow-symlink-publishing#4]
Hi,
since the latest version of Flow/Neos I get the following error message: 

PHP Fatal error:  Declaration of Mw\SymlinkPublishing\Resource\Target\FileSystemSymlinkTarget::publishCollection() must be compatible with TYPO3\Flow\Resource\Target\TargetInterface::publishCollection(TYPO3\Flow\Resource\CollectionInterface $collection) in /[...]/Packages/Application/Mw.SymlinkPublishing/Classes/Mw/SymlinkPublishing/Resource/Target/FileSystemSymlinkTarget.php on line 13

  Type: TYPO3\Flow\Core\Booting\Exception\SubProcessException
  Code: 1355480641
  File: Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php
  Line: 554

**Comment by martin-helmich** [comment]
I was able to reproduce this error. Thanks for reporting!
